<footer>
    <!-- The footer gathers practical project links in one place -->
    <p>&copy; 2026 Sustainable Energy Solutions</p>
    <p>
        <a href="https://minhswin.github.io/COS10026-Applied_Web_Project_Part_1_of_2_-Group-Submission-/">Live Site Link</a> |
        <a href="https://github.com/MinhSwin/COS10026-Applied_Web_Project_Part_1_of_2_-Group-Submission-.git" target="_blank">GitHub Repository</a> |
        <a href="https://cos10026groupproj1.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiNWQ0ZWMxOTNmN2FjNDhjY2FlYzMwYTlkZjIyMjg2OGYiLCJwIjoiaiJ9" target="_blank">Jira Project</a> |
        <a href="mailto:info@sustainableenergy.com">Email Us</a>
    </p>
</footer>