<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Meta information for SEO and accessibility -->
    <meta name="description" content="Sustainable Energy Solutions Company">
    <meta name="keywords" content="renewable energy, solar, wind">
    <meta name="author" content="Kevin Devaiah Baliyamederira Vinod, Sereyboth Sok, Minh Tran, Jack Nguyen">

    <!-- Responsive layout -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Sustainable Energy Solutions</title>

    <!-- CSS files (shared across all pages) -->
    <link rel="stylesheet" href="styles/style.css">

    
    <!-- Internal CSS (required by assignment) -->
    <style>
        .slogan {
            font-style: italic;
            color: #76fa7d;
        }
    </style>
</head>

<body>

<header>
    <!-- Company logo -->
    <img src="images/green-energy-logo.webp" alt="Solar energy logo" class="logo">

    <!-- Main title -->
    <h1>Sustainable Energy Solutions</h1>

    <!-- Company slogan -->
    <p class="slogan">Powering a Greener Tomorrow</p>

    <!-- Navigation menu -->
    <?php include 'nav.inc'; ?>
</header>